# Generated by Django 4.1.7 on 2023-03-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Services', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
