# Generated by Django 4.1.7 on 2023-03-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
