# Generated by Django 4.1.7 on 2023-03-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0005_rename_imagen_avatar_imagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
