# Generated by Django 4.1.7 on 2023-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen_avatar',
            field=models.ImageField(blank=True, default='Perfil.png', null=True, upload_to='imagenes'),
        ),
    ]
