# Generated by Django 4.1.7 on 2023-03-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0009_alter_avatar_imagen_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
