# Generated by Django 4.1.7 on 2023-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0011_alter_avatar_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
